version: "3.8"
services:
  starspace:
    image: starspace
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./:/home/jovyan/
    # need for jupyter for example
    # ports:
    #   - "8888:8888"   

